### Index Method
GET http://localhost:3000/api/questions

### Successfuly posts a question
POST http://localhost:3000/api/questions
Content-Type: application/json

{
    "question": "Peter piper picked a peck of pickled...",
    "answer": "Peppers"
}

### Unsuccessfuly posts a question
POST http://localhost:3000/api/questions
Content-Type: application/json

{
    "answer": "Peppers"
}

### Show question id: 1
GET http://localhost:3000/api/questions/1

### Child Profile Index Method
GET http://localhost:3000/api/child_profiles

### Successfuly creates a new child
POST http://localhost:3000/api/child_profiles
Content-Type: application/json

{
    "name": "Molly"
}

### Show child id: 1

GET http://localhost:3000/api/child_profiles/6
Content-Type: application/json


### Successfully updates Child Profile 1

PUT http://localhost:3000/api/child_profiles/3
Content-Type: application/json

{
    "name": "Jason"
}

### successfully deletes child with id 1

DELETE http://localhost:3000/api/child_profiles/3


### Creates a user
POST  http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "Joey3",
    "email": "joey3@test.com",
    "password": "joey12321",
    "password_confirmation": "joey12321"
}