### Index Method
GET http://localhost:3000/api/questions

### Successfuly posts a question
POST http://localhost:3000/api/questions
Content-Type: application/json

{
    "question": "Peter piper picked a peck of pickled...",
    "answer": "Peppers"
}

### Unsuccessfuly posts a question
POST http://localhost:3000/api/questions
Content-Type: application/json

{
    "answer": "Peppers"
}

### Show question id: 1
GET http://localhost:3000/api/questions/1




### CHILDREN ROUTES
### Child Profile Index Method
GET http://localhost:3000/api/child_profiles

### Successfuly creates a new child
POST http://localhost:3000/api/child_profiles
Content-Type: application/json

{
    "name": "Molly"
}

### Show child id: 6
GET http://localhost:3000/api/child_profiles/6
Content-Type: application/json


### Successfully updates Child Profile 3
PUT http://localhost:3000/api/child_profiles/3
Content-Type: application/json

{
    "name": "Jason"
}

### successfully deletes child with id 3
DELETE http://localhost:3000/api/child_profiles/3




### WISHLISTS
### Index Method for Wishlists

GET http://localhost:3000/api/wish_lists

### Successfuly posts a wishlist
POST http://localhost:3000/api/wish_lists
Content-Type: application/json

{
    "name": "Wishlist",
    "child_profile_id": 2
}

### Successfully updates Wishlist 2
PUT http://localhost:3000/api/wish_lists/2
Content-Type: application/json

{
    "name": "Christmas Wishlist",
    "child_profile_id": 2
}
### Successfully deletes wishlist 2
DELETE http://localhost:3000/api/wish_lists/2

### Successfully deletes wishlist 1000
DELETE http://localhost:3000/api/wish_lists/1000




### WISHES
### Index Method for Wishes

GET http://localhost:3000/api/wishes

### Successfuly posts a wish
POST http://localhost:3000/api/wishes
Content-Type: application/json

{
    "name": "doll",
    "wish_list_id": 2
}

### adds another wish to the wishlist 2
POST http://localhost:3000/api/wishes
Content-Type: application/json

{
    "name": "fast rocket",
    "wish_list_id": 2
}

### Successfully updates Wish 2
PUT http://localhost:3000/api/wishes/2
Content-Type: application/json

{
    "name": "snow rocket"
}
### Successfully deletes wishlist 2
DELETE http://localhost:3000/api/wishes/2

### Successfully deletes wishlist 1000
DELETE http://localhost:3000/api/wishes/1000
